#!/usr/bin/env python3
#
# disk-info - Show a one-line friendly description of a disk or partition
#
# This file is part of squashdisk, see <https://github.com/MestreLion/squashdisk>
# Copyright (C) 2024 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
# License: GPLv3 or later, at your choice. See <http://www.gnu.org/licenses/gpl>

import sys
try:
    import gi
    gi.require_version("UDisks", "2.0")
    from gi.repository import UDisks
except (ValueError, ImportError) as e:
    sys.exit(f"{e}, try:\n\tsudo apt install gir1.2-udisks-2.0")

def oneliner(device: str):
    """device: /dev/sda, /dev/sda1, /dev/loop1, /dev/loop1p2, ..."""
    path = f"/org/freedesktop/UDisks2/block_devices/{device[5:]}"
    client: UDisks.Client = UDisks.Client.new_sync()
    obj: UDisks.Object = client.get_object(path)
    if obj is None:
        raise FileNotFoundError(f"Device not found: {device}")
    info: UDisks.ObjectInfo = client.get_object_info(obj)
    print(info.get_one_liner())

if __name__ == "__main__":
    if len(sys.argv) <= 1:
        sys.exit(f"Usage: {sys.argv[0]} DEVICE")
    try:
        oneliner(sys.argv[1])
    except Exception as e:
        sys.exit(str(e))
